[template.environment]
  TELEGRAM_BOT_TOKEN = "Paste your Telegram bot token here"
  TELEGRAM_CHAT_ID = "Enter your Telegram chat ID here"
  KOFI_TOKEN = "Paste your Ko-fi token here"
  KOFI_USERNAME = "Enter your Ko-fi username here"
  GIST_TOKEN = "Paste your Gist token here"
  GIST_URL = "Paste your Gist URL here"

[build]
  functions = "netlify/functions"
